# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/brl1547a/TEngine/TEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/brl1547a/TEngine/TEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brl1547a/TEngine/TEngine/CMakeFiles /home/brl1547a/TEngine/TEngine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/brl1547a/TEngine/TEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helloopenGL

# Build rule for target.
helloopenGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloopenGL
.PHONY : helloopenGL

# fast build rule for target.
helloopenGL/fast:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/build
.PHONY : helloopenGL/fast

#=============================================================================
# Target rules for targets named helloopenGL_autogen

# Build rule for target.
helloopenGL_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloopenGL_autogen
.PHONY : helloopenGL_autogen

# fast build rule for target.
helloopenGL_autogen/fast:
	$(MAKE) -f CMakeFiles/helloopenGL_autogen.dir/build.make CMakeFiles/helloopenGL_autogen.dir/build
.PHONY : helloopenGL_autogen/fast

helloopenGL_autogen/mocs_compilation.o: helloopenGL_autogen/mocs_compilation.cpp.o

.PHONY : helloopenGL_autogen/mocs_compilation.o

# target to build an object file
helloopenGL_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/helloopenGL_autogen/mocs_compilation.cpp.o
.PHONY : helloopenGL_autogen/mocs_compilation.cpp.o

helloopenGL_autogen/mocs_compilation.i: helloopenGL_autogen/mocs_compilation.cpp.i

.PHONY : helloopenGL_autogen/mocs_compilation.i

# target to preprocess a source file
helloopenGL_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/helloopenGL_autogen/mocs_compilation.cpp.i
.PHONY : helloopenGL_autogen/mocs_compilation.cpp.i

helloopenGL_autogen/mocs_compilation.s: helloopenGL_autogen/mocs_compilation.cpp.s

.PHONY : helloopenGL_autogen/mocs_compilation.s

# target to generate assembly for a file
helloopenGL_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/helloopenGL_autogen/mocs_compilation.cpp.s
.PHONY : helloopenGL_autogen/mocs_compilation.cpp.s

src/3DObjectParser/objectloader.o: src/3DObjectParser/objectloader.cpp.o

.PHONY : src/3DObjectParser/objectloader.o

# target to build an object file
src/3DObjectParser/objectloader.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objectloader.cpp.o
.PHONY : src/3DObjectParser/objectloader.cpp.o

src/3DObjectParser/objectloader.i: src/3DObjectParser/objectloader.cpp.i

.PHONY : src/3DObjectParser/objectloader.i

# target to preprocess a source file
src/3DObjectParser/objectloader.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objectloader.cpp.i
.PHONY : src/3DObjectParser/objectloader.cpp.i

src/3DObjectParser/objectloader.s: src/3DObjectParser/objectloader.cpp.s

.PHONY : src/3DObjectParser/objectloader.s

# target to generate assembly for a file
src/3DObjectParser/objectloader.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objectloader.cpp.s
.PHONY : src/3DObjectParser/objectloader.cpp.s

src/3DObjectParser/objparser.o: src/3DObjectParser/objparser.cpp.o

.PHONY : src/3DObjectParser/objparser.o

# target to build an object file
src/3DObjectParser/objparser.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objparser.cpp.o
.PHONY : src/3DObjectParser/objparser.cpp.o

src/3DObjectParser/objparser.i: src/3DObjectParser/objparser.cpp.i

.PHONY : src/3DObjectParser/objparser.i

# target to preprocess a source file
src/3DObjectParser/objparser.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objparser.cpp.i
.PHONY : src/3DObjectParser/objparser.cpp.i

src/3DObjectParser/objparser.s: src/3DObjectParser/objparser.cpp.s

.PHONY : src/3DObjectParser/objparser.s

# target to generate assembly for a file
src/3DObjectParser/objparser.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/3DObjectParser/objparser.cpp.s
.PHONY : src/3DObjectParser/objparser.cpp.s

src/Animation/Animation.o: src/Animation/Animation.cpp.o

.PHONY : src/Animation/Animation.o

# target to build an object file
src/Animation/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Animation/Animation.cpp.o
.PHONY : src/Animation/Animation.cpp.o

src/Animation/Animation.i: src/Animation/Animation.cpp.i

.PHONY : src/Animation/Animation.i

# target to preprocess a source file
src/Animation/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Animation/Animation.cpp.i
.PHONY : src/Animation/Animation.cpp.i

src/Animation/Animation.s: src/Animation/Animation.cpp.s

.PHONY : src/Animation/Animation.s

# target to generate assembly for a file
src/Animation/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Animation/Animation.cpp.s
.PHONY : src/Animation/Animation.cpp.s

src/BRDF/brdf.o: src/BRDF/brdf.cpp.o

.PHONY : src/BRDF/brdf.o

# target to build an object file
src/BRDF/brdf.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/BRDF/brdf.cpp.o
.PHONY : src/BRDF/brdf.cpp.o

src/BRDF/brdf.i: src/BRDF/brdf.cpp.i

.PHONY : src/BRDF/brdf.i

# target to preprocess a source file
src/BRDF/brdf.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/BRDF/brdf.cpp.i
.PHONY : src/BRDF/brdf.cpp.i

src/BRDF/brdf.s: src/BRDF/brdf.cpp.s

.PHONY : src/BRDF/brdf.s

# target to generate assembly for a file
src/BRDF/brdf.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/BRDF/brdf.cpp.s
.PHONY : src/BRDF/brdf.cpp.s

src/Bone/bone.o: src/Bone/bone.cpp.o

.PHONY : src/Bone/bone.o

# target to build an object file
src/Bone/bone.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Bone/bone.cpp.o
.PHONY : src/Bone/bone.cpp.o

src/Bone/bone.i: src/Bone/bone.cpp.i

.PHONY : src/Bone/bone.i

# target to preprocess a source file
src/Bone/bone.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Bone/bone.cpp.i
.PHONY : src/Bone/bone.cpp.i

src/Bone/bone.s: src/Bone/bone.cpp.s

.PHONY : src/Bone/bone.s

# target to generate assembly for a file
src/Bone/bone.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Bone/bone.cpp.s
.PHONY : src/Bone/bone.cpp.s

src/Materials/Imported3DModel.o: src/Materials/Imported3DModel.cpp.o

.PHONY : src/Materials/Imported3DModel.o

# target to build an object file
src/Materials/Imported3DModel.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/Imported3DModel.cpp.o
.PHONY : src/Materials/Imported3DModel.cpp.o

src/Materials/Imported3DModel.i: src/Materials/Imported3DModel.cpp.i

.PHONY : src/Materials/Imported3DModel.i

# target to preprocess a source file
src/Materials/Imported3DModel.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/Imported3DModel.cpp.i
.PHONY : src/Materials/Imported3DModel.cpp.i

src/Materials/Imported3DModel.s: src/Materials/Imported3DModel.cpp.s

.PHONY : src/Materials/Imported3DModel.s

# target to generate assembly for a file
src/Materials/Imported3DModel.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/Imported3DModel.cpp.s
.PHONY : src/Materials/Imported3DModel.cpp.s

src/Materials/bspline.o: src/Materials/bspline.cpp.o

.PHONY : src/Materials/bspline.o

# target to build an object file
src/Materials/bspline.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bspline.cpp.o
.PHONY : src/Materials/bspline.cpp.o

src/Materials/bspline.i: src/Materials/bspline.cpp.i

.PHONY : src/Materials/bspline.i

# target to preprocess a source file
src/Materials/bspline.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bspline.cpp.i
.PHONY : src/Materials/bspline.cpp.i

src/Materials/bspline.s: src/Materials/bspline.cpp.s

.PHONY : src/Materials/bspline.s

# target to generate assembly for a file
src/Materials/bspline.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bspline.cpp.s
.PHONY : src/Materials/bspline.cpp.s

src/Materials/bsplinepatch.o: src/Materials/bsplinepatch.cpp.o

.PHONY : src/Materials/bsplinepatch.o

# target to build an object file
src/Materials/bsplinepatch.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bsplinepatch.cpp.o
.PHONY : src/Materials/bsplinepatch.cpp.o

src/Materials/bsplinepatch.i: src/Materials/bsplinepatch.cpp.i

.PHONY : src/Materials/bsplinepatch.i

# target to preprocess a source file
src/Materials/bsplinepatch.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bsplinepatch.cpp.i
.PHONY : src/Materials/bsplinepatch.cpp.i

src/Materials/bsplinepatch.s: src/Materials/bsplinepatch.cpp.s

.PHONY : src/Materials/bsplinepatch.s

# target to generate assembly for a file
src/Materials/bsplinepatch.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/bsplinepatch.cpp.s
.PHONY : src/Materials/bsplinepatch.cpp.s

src/Materials/composed3dobject.o: src/Materials/composed3dobject.cpp.o

.PHONY : src/Materials/composed3dobject.o

# target to build an object file
src/Materials/composed3dobject.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/composed3dobject.cpp.o
.PHONY : src/Materials/composed3dobject.cpp.o

src/Materials/composed3dobject.i: src/Materials/composed3dobject.cpp.i

.PHONY : src/Materials/composed3dobject.i

# target to preprocess a source file
src/Materials/composed3dobject.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/composed3dobject.cpp.i
.PHONY : src/Materials/composed3dobject.cpp.i

src/Materials/composed3dobject.s: src/Materials/composed3dobject.cpp.s

.PHONY : src/Materials/composed3dobject.s

# target to generate assembly for a file
src/Materials/composed3dobject.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/composed3dobject.cpp.s
.PHONY : src/Materials/composed3dobject.cpp.s

src/Materials/cylinder.o: src/Materials/cylinder.cpp.o

.PHONY : src/Materials/cylinder.o

# target to build an object file
src/Materials/cylinder.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/cylinder.cpp.o
.PHONY : src/Materials/cylinder.cpp.o

src/Materials/cylinder.i: src/Materials/cylinder.cpp.i

.PHONY : src/Materials/cylinder.i

# target to preprocess a source file
src/Materials/cylinder.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/cylinder.cpp.i
.PHONY : src/Materials/cylinder.cpp.i

src/Materials/cylinder.s: src/Materials/cylinder.cpp.s

.PHONY : src/Materials/cylinder.s

# target to generate assembly for a file
src/Materials/cylinder.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/cylinder.cpp.s
.PHONY : src/Materials/cylinder.cpp.s

src/Materials/light.o: src/Materials/light.cpp.o

.PHONY : src/Materials/light.o

# target to build an object file
src/Materials/light.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/light.cpp.o
.PHONY : src/Materials/light.cpp.o

src/Materials/light.i: src/Materials/light.cpp.i

.PHONY : src/Materials/light.i

# target to preprocess a source file
src/Materials/light.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/light.cpp.i
.PHONY : src/Materials/light.cpp.i

src/Materials/light.s: src/Materials/light.cpp.s

.PHONY : src/Materials/light.s

# target to generate assembly for a file
src/Materials/light.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/light.cpp.s
.PHONY : src/Materials/light.cpp.s

src/Materials/material.o: src/Materials/material.cpp.o

.PHONY : src/Materials/material.o

# target to build an object file
src/Materials/material.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material.cpp.o
.PHONY : src/Materials/material.cpp.o

src/Materials/material.i: src/Materials/material.cpp.i

.PHONY : src/Materials/material.i

# target to preprocess a source file
src/Materials/material.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material.cpp.i
.PHONY : src/Materials/material.cpp.i

src/Materials/material.s: src/Materials/material.cpp.s

.PHONY : src/Materials/material.s

# target to generate assembly for a file
src/Materials/material.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material.cpp.s
.PHONY : src/Materials/material.cpp.s

src/Materials/material3DObject.o: src/Materials/material3DObject.cpp.o

.PHONY : src/Materials/material3DObject.o

# target to build an object file
src/Materials/material3DObject.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material3DObject.cpp.o
.PHONY : src/Materials/material3DObject.cpp.o

src/Materials/material3DObject.i: src/Materials/material3DObject.cpp.i

.PHONY : src/Materials/material3DObject.i

# target to preprocess a source file
src/Materials/material3DObject.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material3DObject.cpp.i
.PHONY : src/Materials/material3DObject.cpp.i

src/Materials/material3DObject.s: src/Materials/material3DObject.cpp.s

.PHONY : src/Materials/material3DObject.s

# target to generate assembly for a file
src/Materials/material3DObject.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/material3DObject.cpp.s
.PHONY : src/Materials/material3DObject.cpp.s

src/Materials/spheres.o: src/Materials/spheres.cpp.o

.PHONY : src/Materials/spheres.o

# target to build an object file
src/Materials/spheres.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/spheres.cpp.o
.PHONY : src/Materials/spheres.cpp.o

src/Materials/spheres.i: src/Materials/spheres.cpp.i

.PHONY : src/Materials/spheres.i

# target to preprocess a source file
src/Materials/spheres.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/spheres.cpp.i
.PHONY : src/Materials/spheres.cpp.i

src/Materials/spheres.s: src/Materials/spheres.cpp.s

.PHONY : src/Materials/spheres.s

# target to generate assembly for a file
src/Materials/spheres.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Materials/spheres.cpp.s
.PHONY : src/Materials/spheres.cpp.s

src/MeshManager/meshmanager.o: src/MeshManager/meshmanager.cpp.o

.PHONY : src/MeshManager/meshmanager.o

# target to build an object file
src/MeshManager/meshmanager.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/MeshManager/meshmanager.cpp.o
.PHONY : src/MeshManager/meshmanager.cpp.o

src/MeshManager/meshmanager.i: src/MeshManager/meshmanager.cpp.i

.PHONY : src/MeshManager/meshmanager.i

# target to preprocess a source file
src/MeshManager/meshmanager.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/MeshManager/meshmanager.cpp.i
.PHONY : src/MeshManager/meshmanager.cpp.i

src/MeshManager/meshmanager.s: src/MeshManager/meshmanager.cpp.s

.PHONY : src/MeshManager/meshmanager.s

# target to generate assembly for a file
src/MeshManager/meshmanager.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/MeshManager/meshmanager.cpp.s
.PHONY : src/MeshManager/meshmanager.cpp.s

src/RenderObject/gbuffer.o: src/RenderObject/gbuffer.cpp.o

.PHONY : src/RenderObject/gbuffer.o

# target to build an object file
src/RenderObject/gbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/gbuffer.cpp.o
.PHONY : src/RenderObject/gbuffer.cpp.o

src/RenderObject/gbuffer.i: src/RenderObject/gbuffer.cpp.i

.PHONY : src/RenderObject/gbuffer.i

# target to preprocess a source file
src/RenderObject/gbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/gbuffer.cpp.i
.PHONY : src/RenderObject/gbuffer.cpp.i

src/RenderObject/gbuffer.s: src/RenderObject/gbuffer.cpp.s

.PHONY : src/RenderObject/gbuffer.s

# target to generate assembly for a file
src/RenderObject/gbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/gbuffer.cpp.s
.PHONY : src/RenderObject/gbuffer.cpp.s

src/RenderObject/renderobject.o: src/RenderObject/renderobject.cpp.o

.PHONY : src/RenderObject/renderobject.o

# target to build an object file
src/RenderObject/renderobject.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/renderobject.cpp.o
.PHONY : src/RenderObject/renderobject.cpp.o

src/RenderObject/renderobject.i: src/RenderObject/renderobject.cpp.i

.PHONY : src/RenderObject/renderobject.i

# target to preprocess a source file
src/RenderObject/renderobject.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/renderobject.cpp.i
.PHONY : src/RenderObject/renderobject.cpp.i

src/RenderObject/renderobject.s: src/RenderObject/renderobject.cpp.s

.PHONY : src/RenderObject/renderobject.s

# target to generate assembly for a file
src/RenderObject/renderobject.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/renderobject.cpp.s
.PHONY : src/RenderObject/renderobject.cpp.s

src/RenderObject/ssaoblurbuffer.o: src/RenderObject/ssaoblurbuffer.cpp.o

.PHONY : src/RenderObject/ssaoblurbuffer.o

# target to build an object file
src/RenderObject/ssaoblurbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaoblurbuffer.cpp.o
.PHONY : src/RenderObject/ssaoblurbuffer.cpp.o

src/RenderObject/ssaoblurbuffer.i: src/RenderObject/ssaoblurbuffer.cpp.i

.PHONY : src/RenderObject/ssaoblurbuffer.i

# target to preprocess a source file
src/RenderObject/ssaoblurbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaoblurbuffer.cpp.i
.PHONY : src/RenderObject/ssaoblurbuffer.cpp.i

src/RenderObject/ssaoblurbuffer.s: src/RenderObject/ssaoblurbuffer.cpp.s

.PHONY : src/RenderObject/ssaoblurbuffer.s

# target to generate assembly for a file
src/RenderObject/ssaoblurbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaoblurbuffer.cpp.s
.PHONY : src/RenderObject/ssaoblurbuffer.cpp.s

src/RenderObject/ssaobuffer.o: src/RenderObject/ssaobuffer.cpp.o

.PHONY : src/RenderObject/ssaobuffer.o

# target to build an object file
src/RenderObject/ssaobuffer.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaobuffer.cpp.o
.PHONY : src/RenderObject/ssaobuffer.cpp.o

src/RenderObject/ssaobuffer.i: src/RenderObject/ssaobuffer.cpp.i

.PHONY : src/RenderObject/ssaobuffer.i

# target to preprocess a source file
src/RenderObject/ssaobuffer.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaobuffer.cpp.i
.PHONY : src/RenderObject/ssaobuffer.cpp.i

src/RenderObject/ssaobuffer.s: src/RenderObject/ssaobuffer.cpp.s

.PHONY : src/RenderObject/ssaobuffer.s

# target to generate assembly for a file
src/RenderObject/ssaobuffer.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/ssaobuffer.cpp.s
.PHONY : src/RenderObject/ssaobuffer.cpp.s

src/RenderObject/testbuffer.o: src/RenderObject/testbuffer.cpp.o

.PHONY : src/RenderObject/testbuffer.o

# target to build an object file
src/RenderObject/testbuffer.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/testbuffer.cpp.o
.PHONY : src/RenderObject/testbuffer.cpp.o

src/RenderObject/testbuffer.i: src/RenderObject/testbuffer.cpp.i

.PHONY : src/RenderObject/testbuffer.i

# target to preprocess a source file
src/RenderObject/testbuffer.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/testbuffer.cpp.i
.PHONY : src/RenderObject/testbuffer.cpp.i

src/RenderObject/testbuffer.s: src/RenderObject/testbuffer.cpp.s

.PHONY : src/RenderObject/testbuffer.s

# target to generate assembly for a file
src/RenderObject/testbuffer.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/RenderObject/testbuffer.cpp.s
.PHONY : src/RenderObject/testbuffer.cpp.s

src/ShaderManager/shaderloader.o: src/ShaderManager/shaderloader.cpp.o

.PHONY : src/ShaderManager/shaderloader.o

# target to build an object file
src/ShaderManager/shaderloader.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shaderloader.cpp.o
.PHONY : src/ShaderManager/shaderloader.cpp.o

src/ShaderManager/shaderloader.i: src/ShaderManager/shaderloader.cpp.i

.PHONY : src/ShaderManager/shaderloader.i

# target to preprocess a source file
src/ShaderManager/shaderloader.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shaderloader.cpp.i
.PHONY : src/ShaderManager/shaderloader.cpp.i

src/ShaderManager/shaderloader.s: src/ShaderManager/shaderloader.cpp.s

.PHONY : src/ShaderManager/shaderloader.s

# target to generate assembly for a file
src/ShaderManager/shaderloader.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shaderloader.cpp.s
.PHONY : src/ShaderManager/shaderloader.cpp.s

src/ShaderManager/shadermanager.o: src/ShaderManager/shadermanager.cpp.o

.PHONY : src/ShaderManager/shadermanager.o

# target to build an object file
src/ShaderManager/shadermanager.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shadermanager.cpp.o
.PHONY : src/ShaderManager/shadermanager.cpp.o

src/ShaderManager/shadermanager.i: src/ShaderManager/shadermanager.cpp.i

.PHONY : src/ShaderManager/shadermanager.i

# target to preprocess a source file
src/ShaderManager/shadermanager.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shadermanager.cpp.i
.PHONY : src/ShaderManager/shadermanager.cpp.i

src/ShaderManager/shadermanager.s: src/ShaderManager/shadermanager.cpp.s

.PHONY : src/ShaderManager/shadermanager.s

# target to generate assembly for a file
src/ShaderManager/shadermanager.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/ShaderManager/shadermanager.cpp.s
.PHONY : src/ShaderManager/shadermanager.cpp.s

src/Texture/texture.o: src/Texture/texture.cpp.o

.PHONY : src/Texture/texture.o

# target to build an object file
src/Texture/texture.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Texture/texture.cpp.o
.PHONY : src/Texture/texture.cpp.o

src/Texture/texture.i: src/Texture/texture.cpp.i

.PHONY : src/Texture/texture.i

# target to preprocess a source file
src/Texture/texture.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Texture/texture.cpp.i
.PHONY : src/Texture/texture.cpp.i

src/Texture/texture.s: src/Texture/texture.cpp.s

.PHONY : src/Texture/texture.s

# target to generate assembly for a file
src/Texture/texture.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/Texture/texture.cpp.s
.PHONY : src/Texture/texture.cpp.s

src/hello_3dObjScene/Scene3DObjects.o: src/hello_3dObjScene/Scene3DObjects.cpp.o

.PHONY : src/hello_3dObjScene/Scene3DObjects.o

# target to build an object file
src/hello_3dObjScene/Scene3DObjects.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_3dObjScene/Scene3DObjects.cpp.o
.PHONY : src/hello_3dObjScene/Scene3DObjects.cpp.o

src/hello_3dObjScene/Scene3DObjects.i: src/hello_3dObjScene/Scene3DObjects.cpp.i

.PHONY : src/hello_3dObjScene/Scene3DObjects.i

# target to preprocess a source file
src/hello_3dObjScene/Scene3DObjects.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_3dObjScene/Scene3DObjects.cpp.i
.PHONY : src/hello_3dObjScene/Scene3DObjects.cpp.i

src/hello_3dObjScene/Scene3DObjects.s: src/hello_3dObjScene/Scene3DObjects.cpp.s

.PHONY : src/hello_3dObjScene/Scene3DObjects.s

# target to generate assembly for a file
src/hello_3dObjScene/Scene3DObjects.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_3dObjScene/Scene3DObjects.cpp.s
.PHONY : src/hello_3dObjScene/Scene3DObjects.cpp.s

src/hello_camera/camera.o: src/hello_camera/camera.cpp.o

.PHONY : src/hello_camera/camera.o

# target to build an object file
src/hello_camera/camera.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/camera.cpp.o
.PHONY : src/hello_camera/camera.cpp.o

src/hello_camera/camera.i: src/hello_camera/camera.cpp.i

.PHONY : src/hello_camera/camera.i

# target to preprocess a source file
src/hello_camera/camera.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/camera.cpp.i
.PHONY : src/hello_camera/camera.cpp.i

src/hello_camera/camera.s: src/hello_camera/camera.cpp.s

.PHONY : src/hello_camera/camera.s

# target to generate assembly for a file
src/hello_camera/camera.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/camera.cpp.s
.PHONY : src/hello_camera/camera.cpp.s

src/hello_camera/hellocamera.o: src/hello_camera/hellocamera.cpp.o

.PHONY : src/hello_camera/hellocamera.o

# target to build an object file
src/hello_camera/hellocamera.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/hellocamera.cpp.o
.PHONY : src/hello_camera/hellocamera.cpp.o

src/hello_camera/hellocamera.i: src/hello_camera/hellocamera.cpp.i

.PHONY : src/hello_camera/hellocamera.i

# target to preprocess a source file
src/hello_camera/hellocamera.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/hellocamera.cpp.i
.PHONY : src/hello_camera/hellocamera.cpp.i

src/hello_camera/hellocamera.s: src/hello_camera/hellocamera.cpp.s

.PHONY : src/hello_camera/hellocamera.s

# target to generate assembly for a file
src/hello_camera/hellocamera.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_camera/hellocamera.cpp.s
.PHONY : src/hello_camera/hellocamera.cpp.s

src/hello_spheres/hellospheres.o: src/hello_spheres/hellospheres.cpp.o

.PHONY : src/hello_spheres/hellospheres.o

# target to build an object file
src/hello_spheres/hellospheres.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_spheres/hellospheres.cpp.o
.PHONY : src/hello_spheres/hellospheres.cpp.o

src/hello_spheres/hellospheres.i: src/hello_spheres/hellospheres.cpp.i

.PHONY : src/hello_spheres/hellospheres.i

# target to preprocess a source file
src/hello_spheres/hellospheres.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_spheres/hellospheres.cpp.i
.PHONY : src/hello_spheres/hellospheres.cpp.i

src/hello_spheres/hellospheres.s: src/hello_spheres/hellospheres.cpp.s

.PHONY : src/hello_spheres/hellospheres.s

# target to generate assembly for a file
src/hello_spheres/hellospheres.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_spheres/hellospheres.cpp.s
.PHONY : src/hello_spheres/hellospheres.cpp.s

src/hello_triangles/hellotriangles.o: src/hello_triangles/hellotriangles.cpp.o

.PHONY : src/hello_triangles/hellotriangles.o

# target to build an object file
src/hello_triangles/hellotriangles.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_triangles/hellotriangles.cpp.o
.PHONY : src/hello_triangles/hellotriangles.cpp.o

src/hello_triangles/hellotriangles.i: src/hello_triangles/hellotriangles.cpp.i

.PHONY : src/hello_triangles/hellotriangles.i

# target to preprocess a source file
src/hello_triangles/hellotriangles.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_triangles/hellotriangles.cpp.i
.PHONY : src/hello_triangles/hellotriangles.cpp.i

src/hello_triangles/hellotriangles.s: src/hello_triangles/hellotriangles.cpp.s

.PHONY : src/hello_triangles/hellotriangles.s

# target to generate assembly for a file
src/hello_triangles/hellotriangles.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/hello_triangles/hellotriangles.cpp.s
.PHONY : src/hello_triangles/hellotriangles.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o

.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i

.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s

.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/myopenglwidget.o: src/myopenglwidget.cpp.o

.PHONY : src/myopenglwidget.o

# target to build an object file
src/myopenglwidget.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/myopenglwidget.cpp.o
.PHONY : src/myopenglwidget.cpp.o

src/myopenglwidget.i: src/myopenglwidget.cpp.i

.PHONY : src/myopenglwidget.i

# target to preprocess a source file
src/myopenglwidget.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/myopenglwidget.cpp.i
.PHONY : src/myopenglwidget.cpp.i

src/myopenglwidget.s: src/myopenglwidget.cpp.s

.PHONY : src/myopenglwidget.s

# target to generate assembly for a file
src/myopenglwidget.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/myopenglwidget.cpp.s
.PHONY : src/myopenglwidget.cpp.s

src/scene.o: src/scene.cpp.o

.PHONY : src/scene.o

# target to build an object file
src/scene.cpp.o:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/scene.cpp.o
.PHONY : src/scene.cpp.o

src/scene.i: src/scene.cpp.i

.PHONY : src/scene.i

# target to preprocess a source file
src/scene.cpp.i:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/scene.cpp.i
.PHONY : src/scene.cpp.i

src/scene.s: src/scene.cpp.s

.PHONY : src/scene.s

# target to generate assembly for a file
src/scene.cpp.s:
	$(MAKE) -f CMakeFiles/helloopenGL.dir/build.make CMakeFiles/helloopenGL.dir/src/scene.cpp.s
.PHONY : src/scene.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... helloopenGL"
	@echo "... edit_cache"
	@echo "... helloopenGL_autogen"
	@echo "... helloopenGL_autogen/mocs_compilation.o"
	@echo "... helloopenGL_autogen/mocs_compilation.i"
	@echo "... helloopenGL_autogen/mocs_compilation.s"
	@echo "... src/3DObjectParser/objectloader.o"
	@echo "... src/3DObjectParser/objectloader.i"
	@echo "... src/3DObjectParser/objectloader.s"
	@echo "... src/3DObjectParser/objparser.o"
	@echo "... src/3DObjectParser/objparser.i"
	@echo "... src/3DObjectParser/objparser.s"
	@echo "... src/Animation/Animation.o"
	@echo "... src/Animation/Animation.i"
	@echo "... src/Animation/Animation.s"
	@echo "... src/BRDF/brdf.o"
	@echo "... src/BRDF/brdf.i"
	@echo "... src/BRDF/brdf.s"
	@echo "... src/Bone/bone.o"
	@echo "... src/Bone/bone.i"
	@echo "... src/Bone/bone.s"
	@echo "... src/Materials/Imported3DModel.o"
	@echo "... src/Materials/Imported3DModel.i"
	@echo "... src/Materials/Imported3DModel.s"
	@echo "... src/Materials/bspline.o"
	@echo "... src/Materials/bspline.i"
	@echo "... src/Materials/bspline.s"
	@echo "... src/Materials/bsplinepatch.o"
	@echo "... src/Materials/bsplinepatch.i"
	@echo "... src/Materials/bsplinepatch.s"
	@echo "... src/Materials/composed3dobject.o"
	@echo "... src/Materials/composed3dobject.i"
	@echo "... src/Materials/composed3dobject.s"
	@echo "... src/Materials/cylinder.o"
	@echo "... src/Materials/cylinder.i"
	@echo "... src/Materials/cylinder.s"
	@echo "... src/Materials/light.o"
	@echo "... src/Materials/light.i"
	@echo "... src/Materials/light.s"
	@echo "... src/Materials/material.o"
	@echo "... src/Materials/material.i"
	@echo "... src/Materials/material.s"
	@echo "... src/Materials/material3DObject.o"
	@echo "... src/Materials/material3DObject.i"
	@echo "... src/Materials/material3DObject.s"
	@echo "... src/Materials/spheres.o"
	@echo "... src/Materials/spheres.i"
	@echo "... src/Materials/spheres.s"
	@echo "... src/MeshManager/meshmanager.o"
	@echo "... src/MeshManager/meshmanager.i"
	@echo "... src/MeshManager/meshmanager.s"
	@echo "... src/RenderObject/gbuffer.o"
	@echo "... src/RenderObject/gbuffer.i"
	@echo "... src/RenderObject/gbuffer.s"
	@echo "... src/RenderObject/renderobject.o"
	@echo "... src/RenderObject/renderobject.i"
	@echo "... src/RenderObject/renderobject.s"
	@echo "... src/RenderObject/ssaoblurbuffer.o"
	@echo "... src/RenderObject/ssaoblurbuffer.i"
	@echo "... src/RenderObject/ssaoblurbuffer.s"
	@echo "... src/RenderObject/ssaobuffer.o"
	@echo "... src/RenderObject/ssaobuffer.i"
	@echo "... src/RenderObject/ssaobuffer.s"
	@echo "... src/RenderObject/testbuffer.o"
	@echo "... src/RenderObject/testbuffer.i"
	@echo "... src/RenderObject/testbuffer.s"
	@echo "... src/ShaderManager/shaderloader.o"
	@echo "... src/ShaderManager/shaderloader.i"
	@echo "... src/ShaderManager/shaderloader.s"
	@echo "... src/ShaderManager/shadermanager.o"
	@echo "... src/ShaderManager/shadermanager.i"
	@echo "... src/ShaderManager/shadermanager.s"
	@echo "... src/Texture/texture.o"
	@echo "... src/Texture/texture.i"
	@echo "... src/Texture/texture.s"
	@echo "... src/hello_3dObjScene/Scene3DObjects.o"
	@echo "... src/hello_3dObjScene/Scene3DObjects.i"
	@echo "... src/hello_3dObjScene/Scene3DObjects.s"
	@echo "... src/hello_camera/camera.o"
	@echo "... src/hello_camera/camera.i"
	@echo "... src/hello_camera/camera.s"
	@echo "... src/hello_camera/hellocamera.o"
	@echo "... src/hello_camera/hellocamera.i"
	@echo "... src/hello_camera/hellocamera.s"
	@echo "... src/hello_spheres/hellospheres.o"
	@echo "... src/hello_spheres/hellospheres.i"
	@echo "... src/hello_spheres/hellospheres.s"
	@echo "... src/hello_triangles/hellotriangles.o"
	@echo "... src/hello_triangles/hellotriangles.i"
	@echo "... src/hello_triangles/hellotriangles.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/myopenglwidget.o"
	@echo "... src/myopenglwidget.i"
	@echo "... src/myopenglwidget.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

